### ISSUE TITLE
vLEI Beta - Get Started no longer works

### ISSUE THREAD

**Issue by psteniusubi** [WebOfTrust/vLEI#18]
I'm trying to complete Technical Setup with fresh docker images and containers, but the Get Started command now does nothing.

With a previous set of containers Get Started did work, a credential appeared in my wallet and I could complete Technical Setup.

Please advice.

**Comment by m00sey** [comment]
@psteniusubi Thanks for opening the issue, we have restarted one of the agents as it appears that stopped responding and so your subsequent requests were failing.

You should be able to restart your containers and complete technical setup.

**Comment by psteniusubi** [comment]
Thanks for your response. However Get Started still does nothing.
First I tried Get Started command after simply starting my stopped container.
Then I tried Get Started command from a fresh image.
Nothing happens. There are no errors or messages shown in the browser or in any of my containers console logs.

**Comment by m00sey** [comment]
We're continuing to look into your issue. 

I will update here with further information.

**Comment by m00sey** [comment]
@psteniusubi My co-worker and I have been through the flows now, we can both successfully receive the QVI credential after clicking get started.

Can you try stopping, deleting and re-pulling the containers.

Once the QVI container is running can confirm in Settings -> Address Book the GLEIF AID is `EZ921Tv_rdgIiHURHiWwyG8vW6R69QN2sCOYUDUvfCN0` please?

**Comment by rc-provenant** [comment]
Ran into the same issue today and following the recommendation to stop, delete and re-pull the containers.  I was able to receive the QVI credential after clicking "get started".

**Comment by psteniusubi** [comment]
Now I think this works

First I tried with existing images by only removing containers. This did not work
Then I remove images and try again. This worked.

Was there an update to the images in between? The tag version has not changed

**Comment by m00sey** [comment]
@psteniusubi there have been no changes to the docker container.
