### ISSUE TITLE
vLEI Credential issued by a Qualified vLEI Issuer and added to the OOR Holder’s digital wallet does not appear in OOR Holder's wallet

### ISSUE THREAD

**Issue by rc-provenant** [WebOfTrust/vLEI#23]
I successfully completed Functional Scenario step 1.1, issuing a credential to a legal entity.  
In step 1.2, I receive a notification that the credential was successfully issued to the OOR Holder's digital wallet, but the credential is not in Jane Smith's wallet.

**Comment by psteniusubi** [comment]
I'm experiencing the same issue. Credential issued to Jane Smith does not appear in Jane Smith's wallet.

**Comment by m00sey** [comment]
@rc-provenant @psteniusubi  OK, we're looking into this.

**Comment by m00sey** [comment]
@rc-provenant @psteniusubi a new image has been pushed with additional updates and stability improvements.

We have also re-deployed the supporting infrastructure.

You need to stop, delete and and pull `latest` for each container.

**Comment by rc-provenant** [comment]
Followed above directions, it now works.

**Comment by psteniusubi** [comment]
On first run this did not work. Legal Entity credential did not appear in ACME's wallet.

On second run I was able to complete all three issuing steps.

**Comment by m00sey** [comment]
@rc-provenant within the last hour we have deployed a new set of infrastructure. With enhancements based off of what we were seeing from people running through the functional scenarios.

If you could go ahead and stop, delete and pull the containers again and restart the functional scenarios we'll be monitoring things on our end.

We appreciate the you taking the time to work through these issues with us!
Feel free to close this issue if you have a successful test :)

**Comment by m00sey** [comment]
Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software
