### ISSUE TITLE
vLEI Credential issued by a Qualified vLEI Issuer and added to the Engagement Context Role Holder’s digital wallet does not appear in John Doe's wallet

### ISSUE THREAD

**Issue by rc-provenant** [WebOfTrust/vLEI#24]
In 3rd scenario, step 1.3, I received a notification that the credential was successfully issued to the Legal Entity Engagement Context Role Holder's digital wallet, but the credential is not in John Doe's wallet.

**Comment by rc-provenant** [comment]
I stopped, deleted and recreated all containers, to try again, and now my get started is not working.

**Comment by m00sey** [comment]
@rc-provenant we're seeing a large number of errors in the infrastructure that are causing restarts so we're going to re-deploy.

I will update here when we're done and have finished some internal testing. That would be a good time to start running the functional scenarios again.

**Comment by rc-provenant** [comment]
Issues are corrected.  I received the credential in John Doe's wallet

**Comment by psteniusubi** [comment]
Failure on first attempt after resetting everything.
Success on second attempt after again resetting everything.

**Comment by m00sey** [comment]
Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software
