### ISSUE TITLE
Credential Presentation scenario 1 - presentation response missing

### ISSUE THREAD

**Issue by psteniusubi** [WebOfTrust/vLEI#25]
On http://localhost:5123/ I select ACME Corp and Legal Entity vLEI Credential, then click Request. The green popup with text "Request succeeded" shortly appears but then nothing happens.

**Comment by m00sey** [comment]
@psteniusubi we're seeing a large number of errors in the infrastructure that are causing restarts so we're going to re-deploy.

I will update here when we're done and have finished some internal testing. That would be a good time to start running the functional scenarios again.

**Comment by m00sey** [comment]
@psteniusubi within the last hour we have deployed a new set of infrastructure. With enhancements based off of what we were seeing from people running through the functional scenarios.

If you could go ahead and stop, delete and pull the containers again and restart the functional scenarios we'll be monitoring things on our end.

We appreciate the you taking the time to work through these issues with us!
Feel free to close this issue if you have a successful test :)

**Comment by psteniusubi** [comment]
Still nothing happens after clicking Request

This issue is duplicate of #29

**Comment by m00sey** [comment]
Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software
