### ISSUE TITLE
Credential issued dont appear in to holders wallet

### ISSUE THREAD

**Issue by savitaraghuvanshi** [WebOfTrust/vLEI#27]
Hi @SmithSamuelM  , Kindly please help on , I have succesfully tested first functional scenario and while testing second scenario where CEO OOR  need to be assigned to Jhon Smith , I can succesfully issue credentials (with port 5623 UI) , but **issued creds cant be seen in Jhon wallet** . I am checking containers Jhon and qvi logs also but no logs got generated for this there .  FYI:  @rowanshedden

**Comment by m00sey** [comment]
@savitaraghuvanshi within the last hour we have deployed a new set of infrastructure. With enhancements based off of what we were seeing from people running through the functional scenarios.

If you could go ahead and stop, delete and pull the containers again and restart the functional scenarios we'll be monitoring things on our end.

We appreciate the you taking the time to work through these issues with us!
Feel free to close this issue if you have a successful test :)

**Comment by savitaraghuvanshi** [comment]
Thanks for quick update , I am testing now and will update you .

**Comment by savitaraghuvanshi** [comment]
@SmithSamuelM There is a progress , I can now test functional scenario 2 : Jhon Smith can see its OOR VC of  role CEO in its wallet 
**while scenario 3 the same issue . I can issue ECR role but Jhon doe cant see in its wallet ,**

**Comment by m00sey** [comment]
Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software
