### ISSUE TITLE
Issue with Credential Presentation scenario # 1, Legal Entity presents its Legal Entity vLEI Credential

### ISSUE THREAD

**Issue by rc-provenant** [WebOfTrust/vLEI#28]
Issue with Credential Presentation scenario # 1, Legal Entity presents its Legal Entity vLEI Credential.  When I hit request, it says request succeeded, but there is no response in Presentation Responses.

**Comment by psteniusubi** [comment]
I'm experiencing same issue. Reported here #25

**Comment by m00sey** [comment]
@rc-provenant @psteniusubi 

We have seen an intermittent crash in the witness network that is likely the cause of this.
As always, stop, delete container and remove image and repulling should result in a successful run (We do this internally every morning).

We are seeing some old versions of the containers in use.

**Comment by psteniusubi** [comment]
@m00sey 
I just tried again with fresh images.. still nothing appears in the Presentation Responses box

**Comment by m00sey** [comment]
@psteniusubi I pulled and ran this successfully, can you confirm the correct options selected under presentation request?

That's the only thing I can think of, we're not seeing any issues in the deployed infrastructure right now.

<img width="1552" alt="Screen Shot 2021-11-17 at 11 39 31" src="https://user-images.githubusercontent.com/180035/142243157-bfd16883-62ef-41e3-a260-17c8a461a9a6.png">.

**Comment by rc-provenant** [comment]
Hi Kevin,

There's only one option in Get Started, the LEI, which is prepopulated.

[image: image.png]
Ruth

**Comment by psteniusubi** [comment]
@m00sey 

I just tried again.. nothing.

I think my selections look correct

![image](https://user-images.githubusercontent.com/17900263/142245701-36dc6857-27a8-4fc7-98b3-e3b446091520.png)

I waited on this screen a few minutes.. Then hit browser refresh. No response appears

**Comment by m00sey** [comment]
@psteniusubi we'll be sending out invitations to a Zoom workshop where we hope to work through these issues. In the meantime the only resolution we can offer is stop, delete, pull new containers. We're not seeing any infrastructure failures, and we test successfully the workflows ourselves each morning. I am sorry we can't offer a better update, hopefully getting together in the workshop will bring to light any underlying causes.

**Comment by psteniusubi** [comment]
@m00sey are there any updates? 
I today tried again with fresh images, this time "Get started" (#18) did not work. 
Should we wait for things to be fixed, keep on trying, or what is your advice?

**Comment by m00sey** [comment]
@psteniusubi Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software.
