### ISSUE TITLE
Functional Scenario Step 1

### ISSUE THREAD

**Issue by rowanshedden** [WebOfTrust/vLEI#29]
I have set up the QVI issuer as per the instructions and am trying to execute functional scenario step 1.

The dropdown list does not contain ACME Corp. The only selection is GLEIF, and when I try to issue using GLEIF the field for Entity shows as undefined.

Note: I have pulled and restarted docker with the latest images, as per your reply to my original issue.

**Comment by rowanshedden** [comment]
**Update:** 
I decided to start again from scratch, and removed the docker containers and images completely. I went back and set up the environment as per the instructions, pulling the latest images. However, now I am back to square one, and the original issue is happening. The credential that is supposed to be issued when you hit 'Get Started' is not being issued to the wallet. I can't even get back to the Credential Presentation scenario 1 as I do not have the issuer credential in the QVI wallet.

Attached screenshots...

![QVI Wallet - before](https://user-images.githubusercontent.com/16812741/141701960-9166fdc3-883f-47b2-8b6f-b2a451e30a0c.png)
.![QVI Getting Started](https://user-images.githubusercontent.com/16812741/141701948-d5c8b2cb-b9f9-49b2-b224-10b7eb2e94ed.png)
![QVI Wallet - after](https://user-images.githubusercontent.com/16812741/141701956-0216b37d-ed1d-4c02-ac05-863fb9d625f0.png)

**Comment by kpratihast** [comment]
@artikulkarni - Facing similar issue after taking fresh pull of images

**Comment by rowanshedden** [comment]
**Further Update:**
I refreshed my environment - removed and pulled the latest images. I managed to get the initial credential issued but when I tried Functional Scenario Step 1, the ACME Corp is not shown in the dropdown box. There is only GLEIF.

Please advise how to continue or troubleshoot. I am using Chrome as my browser.

**Screenshots** 
Wallet with initial credential:
![Initial credential issued](https://user-images.githubusercontent.com/16812741/142083935-a8b1bc60-bad2-4fe8-a4da-d55464bcee80.png)

No ACME dropdown:
![ACME not in dropdown](https://user-images.githubusercontent.com/16812741/142083995-e879aac9-0caf-4376-be9b-f96c41650295.png)

**Comment by m00sey** [comment]
@rowanshedden we'll be sending out invitations to a Zoom workshop where we hope to work through these issues. In the meantime the only resolution we can offer is stop, delete, pull new containers. We're not seeing any infrastructure failures, and we test successfully the workflows ourselves each morning. I am sorry we can't offer a better update, hopefully getting together in the workshop will bring to light any underlying causes.

**Comment by ASciusco** [comment]
Hi,
for scenario 1, No ACME dropdown.
we noticed via javascript console that:
CONTROLLER_URL: "http: // localhost" is wired, would it be possible to make it dynamic (see screeshot)? we installed the application not locally but on the server used for testing and shared with the IT team.

Thanks!
![kiwi](https://user-images.githubusercontent.com/93254465/143244464-5e9b41b1-6295-4e31-8ef2-018115728d61.png)

**Comment by m00sey** [comment]
@ASciusco apologies for the slow response, last week was Thanksgiving here in the U.S. and most of the team was on vacation.

So the software as currently built isn't meant for a remote deployment, the reason you don't see ACME is it's querying (locally, as you noted) for other instances that are running, this is something that wouldn't be present in a "real world" scenario as connections would be established through an Out Of Band protocol and you'd pick your connection from a contact list (or something similar) 

This method of discovery was added purely so anyone running the containers locally would have access to a "predetermined" set of contacts, without introducing the inherent complexity of OOBI flows.

If you haven't already registered we are have a "beta software deep dive" session scheduled for this week, if you aren't already on it, I would suggest contacting Karla/Arti, whomever sent you the initial beta documents to get on the call. 

We can discuss further then.

**Comment by m00sey** [comment]
Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software
