### ISSUE TITLE
Initiation of Qualification Testing of the vLEI Beta Software

### ISSUE THREAD

**Issue by KLEMENCIZTOK** [WebOfTrust/vLEI#30]
all,

 we have several questions for example:
- what infrastructure do we need to provide in IT (servers, OS, system equipment  Docker,…)
- to where and in what way we must enable communication (internet addresses, protocols, applications)
- what else do we need to provide (security, identifications - certificates, accessibility - SLA)
- whether we need to technically understand the operation (blockchain protocols, infrastructure, implementation)
- whether IT development is also needed (wallet)
- whether IT help is needed when using applications
- any integration with our applications is required, and if so, do we need any new functionalities in our applications 
- whether IT assistance will be required for certification / certification renewal
 
Only after we'll get the above answers we will be able  to initiate the Qualification Testing of vLEI and the approximate time frame.
 
 
Best
 
 
 
 

Iztok Klemenc
INTERNATIONAL IDENTIFICATIONS AND DATA PROVIDING DEPARTMENT
General Manager
 
ANNA Service Bereau TC Chair
ISO TC68/SC8 Member of Fintech Technical Advisory Group 
 
 
KDD - Centralna klirinško depotna družba d.o.o.    Tivolska cesta 48      Mobile / + 386 41 692 317
KDD - Central Securities Clearing Corporation       SI - 1542 Ljubljana   
www.kdd.si  LEI 48510000JZ17NWGUA510

**Comment by m00sey** [comment]
@KLEMENCIZTOK see my answers below:

- what infrastructure do we need to provide in IT
  -  for the beta software, just the docker images we provide

- to where and in what way we must enable communication (internet addresses, protocols, applications)
  - for the beta software, tcp port: 5632, http port: 5642
  
- what else do we need to provide (security, identifications - certificates, accessibility - SLA)
  - none, however access could be intermittent 
  
-  whether we need to technically understand the operation (blockchain protocols, infrastructure, implementation)
  - for the beta software you do not have to understand the technical operations, although we are happy to help with that

- whether IT development is also needed (wallet)
    - for the beta software a version of what can be classed as a wallet is available under the "wallet" tab in the containers, there is currently no third party wallet support.

- whether IT help is needed when using applications
  -  after configuration of the docker software and IT support shouldn't be required.
  
- any integration with our applications is required, and if so, do we need any new functionalities in our applications
  - for the beta software, no.

- whether IT assistance will be required for certification / certification renewal
  - for the beta software, no.
