### ISSUE TITLE
Launch of the vLEI Beta Software Sandbox

### ISSUE THREAD

**Issue by artikulkarni** [WebOfTrust/vLEI#31]
Hi Karla,
 
Thank you for your inputs. The sandbox environment gives us good overview of various actors and their roles in credentialing process. However, it would be great if more clarity can be provided on below points:

- We would like to see what’s happening behind the scenes in terms of more logs (container logs and/or log files) and data (type, format, JSON representation of credentials, etc. ) stored in agent’s wallet
- 
- Container images are behaving differently when updated. After latest update (~14 hrs ago), we were able to issue credentials, though credential presentation scenarios are not working. There’s a bug logged for a similar issue in github which we were facing earlier but got resolved after latest updates
- 
- Details around technical implementation – data serialization, communication between agents, API endpoints for external interface, etc.

 
 
Regards,
Kshitij Pratihast

FYI - kshitij.pratihast@novartis.com

**Comment by artikulkarni** [comment]
> Hi Karla,
> 
> Thank you for your inputs. The sandbox environment gives us good overview of various actors and their roles in credentialing process. However, it would be great if more clarity can be provided on below points:
> 
> * We would like to see what’s happening behind the scenes in terms of more logs (container logs and/or log files) and data (type, format, JSON representation of credentials, etc. ) stored in agent’s wallet
> * Container images are behaving differently when updated. After latest update (~14 hrs ago), we were able to issue credentials, though credential presentation scenarios are not working. There’s a bug logged for a similar issue in github which we were facing earlier but got resolved after latest updates
> * Details around technical implementation – data serialization, communication between agents, API endpoints for external interface, etc.
> 
> Regards, Kshitij Pratihast

**Comment by artikulkarni** [comment]
Response ==> Already sent to requestor

Dear all,
 
A message from the vLEI development team:
 
“The vLEI development team would like to offer an update on the state of the deployed infrastructure.
 
Currently we are running nightly restarts of witness network.  For those participants running through the functional scenarios, each time the scenarios are run on a given day, please be advised that the containers should be stopped, deleted and re-pulled.

The vLEI team will continue to monitor the GitHub issues.”
 
Kind regards,
 
Karla

**Comment by m00sey** [comment]
@artikulkarni do you want me to respond to those questions here?
