### ISSUE TITLE
Issue with Credential Scenario Step 4 - holder wallet not updated

### ISSUE THREAD

**Issue by rc-provenant** [WebOfTrust/vLEI#32]
When revoking the credentials for Acme, Jane Smith, or John Doe, the status is updated to Revoke on the qvi Issued Credentials for the qvi container, but the corresponding holder wallets still show the credential status as Valid.

**Comment by m00sey** [comment]
@rc-provenant thanks for this.

We're seeing this intermittently and looking into the cause.

**Comment by rc-provenant** [comment]
I've tried with fresh images and now, "Get Started" no longer works.

**Comment by m00sey** [comment]
@rc-provenant we'll be sending out invitations to a Zoom workshop where we hope to work through these issues. In the meantime the only resolution we can offer is stop, delete, pull new containers. We're not seeing any infrastructure failures, and we test successfully the workflows ourselves each morning. I am sorry we can't offer a better update, hopefully getting together in the workshop will bring to light any underlying causes.

**Comment by rc-provenant** [comment]
I’m back to the issue with Scenario 4 where the Revoke does not show in the Legal Entity’s (ACME) wallet.  Although when verifying the Legal Entity’s credential, the credential in the Legal Entity’s wallet now shows as Revoked.  The same issue exists with Jane and John, when their credentials are revoked their wallet still shows the credential as “Valid”; but in their case when verifying their credentials, both still show as “Valid”.

**Comment by m00sey** [comment]
Thank you for taking the time to participate in the vLEI Beta software qualification program.

For any remaining open issues lodged during the qualification, the discussion during the deep dive session we ran at the conclusion of the beta qualification has provided answers to these issues.  GLEIF proposes to close these issues and asks you to reach out to your contact at GLEIF for a link to the recording.
 
The vLEI development team will continue to develop the software in preparation for the pilot phase of the vLEI development.  GLEIF would like to thank you again for the contribution of your feedback toward the development of the vLEI Beta software.
